/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dentalclinicsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author akash
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public Dashboard() {
        initComponents();
        
            
        if(user.LogedUserRoll.equals("Admin")){
        receptionistlabel.show();
        doctorlabel.show();
        patientslabel.hide();
        appointmentslabel.hide();
        Treatmentslabel.hide();
        }
        if(user.LogedUserRoll.equals("Doctor")){
        receptionistlabel.hide();
        doctorlabel.hide();
        patientslabel.hide();
        appointmentslabel.hide();
        Treatmentslabel.show();
        }
        if(user.LogedUserRoll.equals("Receptionist")){
        receptionistlabel.hide();
         doctorlabel.hide();
        patientslabel.show();
        appointmentslabel.show();
        Treatmentslabel.hide();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        receptionistlabel = new javax.swing.JLabel();
        Treatmentslabel = new javax.swing.JLabel();
        appointmentslabel = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        patientslabel = new javax.swing.JLabel();
        doctorlabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(169, 434));

        receptionistlabel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        receptionistlabel.setForeground(new java.awt.Color(0, 255, 204));
        receptionistlabel.setText("Receptionists");
        receptionistlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                receptionistlabelMouseClicked(evt);
            }
        });

        Treatmentslabel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Treatmentslabel.setForeground(new java.awt.Color(0, 255, 204));
        Treatmentslabel.setText("Treatments");
        Treatmentslabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TreatmentslabelMouseClicked(evt);
            }
        });

        appointmentslabel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        appointmentslabel.setForeground(new java.awt.Color(0, 255, 204));
        appointmentslabel.setText("Appointments");
        appointmentslabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appointmentslabelMouseClicked(evt);
            }
        });

        logout.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(0, 255, 204));
        logout.setText("Log Out");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 255, 204));
        jLabel14.setText("Dental Clinic ");

        patientslabel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        patientslabel.setForeground(new java.awt.Color(0, 255, 204));
        patientslabel.setText("Patients");
        patientslabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patientslabelMouseClicked(evt);
            }
        });

        doctorlabel.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        doctorlabel.setForeground(new java.awt.Color(0, 255, 204));
        doctorlabel.setText("Doctors");
        doctorlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doctorlabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(logout)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doctorlabel)
                    .addComponent(appointmentslabel)
                    .addComponent(receptionistlabel)
                    .addComponent(jLabel14)
                    .addComponent(Treatmentslabel)
                    .addComponent(patientslabel))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel14)
                .addGap(93, 93, 93)
                .addComponent(doctorlabel)
                .addGap(18, 18, 18)
                .addComponent(Treatmentslabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(patientslabel)
                .addGap(18, 18, 18)
                .addComponent(receptionistlabel)
                .addGap(7, 7, 7)
                .addComponent(appointmentslabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addComponent(logout)
                .addGap(48, 48, 48))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 193, 600);

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel12.setText("Dashboard");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(210, 10, 100, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void receptionistlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_receptionistlabelMouseClicked
    
        new receptionist().setVisible(true);
        this.dispose();   
        
    }//GEN-LAST:event_receptionistlabelMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        user User = new user();
        User.logout();

        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void appointmentslabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appointmentslabelMouseClicked
        new appointments().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_appointmentslabelMouseClicked

    private void patientslabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientslabelMouseClicked
        // TODO add your handling code here:
         new patient().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_patientslabelMouseClicked

    private void TreatmentslabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TreatmentslabelMouseClicked
        new treatment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_TreatmentslabelMouseClicked

    private void doctorlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doctorlabelMouseClicked
        // TODO add your handling code here:
         new doctors().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_doctorlabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Treatmentslabel;
    private javax.swing.JLabel appointmentslabel;
    private javax.swing.JLabel doctorlabel;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel patientslabel;
    private javax.swing.JLabel receptionistlabel;
    // End of variables declaration//GEN-END:variables
}
